version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      android-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:15"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      actions-updates:
        applies-to: version-updates
        patterns:
          - "*"
