package com.amaury.pointage

import android.content.Context
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestore
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

/** Sauvegarde cloud des réglages. La restauration fusionne sans effacer les clés locales absentes du cloud. */
object CloudSettingsBackup {
    private const val COLLECTION="app_backup";private const val DOCUMENT="settings";private const val SCHEMA_VERSION=2L
    fun saveAll(context:Context,onDone:(Boolean,String)->Unit){val user=FirebaseAuth.getInstance().currentUser?:return onDone(false,"Aucun compte Google connecté");val app=context.applicationContext;val payload=runCatching{exportPreferences(app)}.getOrElse{return onDone(false,"Impossible de lire les réglages : ${it.localizedMessage?:it.javaClass.simpleName}")};FirebaseFirestore.getInstance().collection("users").document(user.uid).collection(COLLECTION).document(DOCUMENT).set(hashMapOf("schemaVersion" to SCHEMA_VERSION,"payload" to payload.toString(),"updatedAt" to FieldValue.serverTimestamp())).addOnSuccessListener{onDone(true,"réglages sauvegardés")}.addOnFailureListener{onDone(false,it.localizedMessage?:"Firestore refuse la sauvegarde des réglages")}}
    fun restoreAll(context:Context,onDone:(Boolean,String)->Unit){val user=FirebaseAuth.getInstance().currentUser?:return onDone(false,"Aucun compte Google connecté");val app=context.applicationContext;FirebaseFirestore.getInstance().collection("users").document(user.uid).collection(COLLECTION).document(DOCUMENT).get().addOnSuccessListener{doc->if(!doc.exists())return@addOnSuccessListener onDone(false,"Aucune sauvegarde de réglages trouvée");val payload=doc.getString("payload");if(payload.isNullOrBlank())return@addOnSuccessListener onDone(false,"Sauvegarde de réglages vide : rien n'a été remplacé");val root=runCatching{JSONObject(payload)}.getOrNull();if(root==null||root.length()==0)return@addOnSuccessListener onDone(false,"Sauvegarde de réglages illisible : rien n'a été remplacé");val result=runCatching{importPreferences(app,root)};if(result.isSuccess)onDone(true,"réglages fusionnés sans effacer les données locales") else onDone(false,"Restauration des réglages impossible : ${result.exceptionOrNull()?.localizedMessage?:"erreur inconnue"}")}.addOnFailureListener{onDone(false,it.localizedMessage?:"Firestore refuse la restauration des réglages")}}
    private fun exportPreferences(context:Context):JSONObject{val root=JSONObject();val dir=File(context.applicationInfo.dataDir,"shared_prefs");dir.listFiles().orEmpty().filter{it.isFile&&it.name.endsWith(".xml")}.map{it.name.removeSuffix(".xml")}.filter(::shouldBackup).sorted().forEach{name->val values=JSONObject();context.getSharedPreferences(name,Context.MODE_PRIVATE).all.forEach{(k,v)->when(v){null->Unit;is Boolean,is Int,is Long,is Float,is String->values.put(k,v);is Set<*>->values.put(k,JSONArray(v.filterIsInstance<String>().sorted()))}};root.put(name,values)};return root}
    private fun importPreferences(context:Context,root:JSONObject){for(name in root.keys().asSequence().toList().filter(::shouldBackup)){val values=root.optJSONObject(name)?:continue;val prefs=context.getSharedPreferences(name,Context.MODE_PRIVATE);val editor=prefs.edit();val keys=values.keys();while(keys.hasNext()){val key=keys.next();/* La valeur cloud gagne pour la même clé, mais aucune autre clé locale n'est supprimée. */when(val value=values.opt(key)){is Boolean->editor.putBoolean(key,value);is Int->editor.putInt(key,value);is Long->editor.putLong(key,value);is Double->{val l=value.toLong();if(value==l.toDouble())editor.putLong(key,l) else editor.putFloat(key,value.toFloat())};is String->editor.putString(key,value);is JSONArray->{val set=linkedSetOf<String>();for(i in 0 until value.length())value.optString(i,null)?.let(set::add);editor.putStringSet(key,set)}}};if(!editor.commit())error("Échec d'écriture de $name")}}
    private fun shouldBackup(name:String):Boolean=BackupSecurityPolicy.canTransferPreferenceFile(name)
}
