package com.amaury.pointage

import android.content.Context
import android.graphics.*
import android.util.AttributeSet
import android.widget.Button
import java.util.Collections
import java.util.WeakHashMap
import kotlin.math.*

open class RedDiamondFinalButton @JvmOverloads constructor(context:Context,attrs:AttributeSet?=null,defStyleAttr:Int=android.R.attr.buttonStyle):Button(context,attrs,defStyleAttr){
 companion object{const val RENDER_NAME="Diamant solaire 3D";private const val SEGMENTS=16;private const val FACET_COUNT=80;private const val BASE_ALPHA=166;private const val LIGHT_ALPHA_MAX=255;private val live=Collections.newSetFromMap(WeakHashMap<RedDiamondFinalButton,Boolean>());fun updateGlobalNaturalLight(angle:Float,pitch:Float,roll:Float,intensity:Float,night:Boolean,elevation:Float){live.forEach{it.setNaturalLight(angle,pitch,roll,intensity,night,elevation)}}}
 private data class FacetState(val color:Int,val alpha:Int,var lastIncidence:Float=0f,var lastSpecular:Float=0f,var lastInternal:Float=0f)
 private val fill=Paint(Paint.ANTI_ALIAS_FLAG);private val edge=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE};private val states=arrayOfNulls<FacetState>(FACET_COUNT)
 private var lightAngle=-55f;private var pitch=0f;private var roll=0f;private var intensity=.78f;private var night=false;private var elevation=45f;private var lensStrength=.50f
 open fun diamondPalette()=intArrayOf(Color.rgb(255,38,62),Color.rgb(255,0,34),Color.rgb(224,0,28),Color.rgb(255,68,86),Color.rgb(196,0,25),Color.rgb(255,12,44),Color.rgb(242,0,34),Color.rgb(255,94,108),Color.rgb(212,0,30),Color.rgb(255,24,50),Color.rgb(232,0,34),Color.rgb(255,54,74),Color.rgb(184,0,24),Color.rgb(255,6,40),Color.rgb(248,0,36),Color.rgb(255,78,96));open fun diamondTint()=Color.rgb(255,18,48);open fun diamondDark()=Color.rgb(150,0,22);open fun diamondHighlight()=Color.rgb(255,238,243)
 init{background=null;stateListAnimator=null;setPadding(0,0,0,0);isAllCaps=false}
 override fun onAttachedToWindow(){super.onAttachedToWindow();live.add(this)};override fun onDetachedFromWindow(){live.remove(this);super.onDetachedFromWindow()}
 fun setDiamondLightAngle(a:Float){setNaturalLight(a,pitch,roll,intensity,night,elevation)};fun setLensStrength(v:Float){lensStrength=v.coerceIn(0f,1f);invalidate()};private fun setNaturalLight(a:Float,p:Float,r:Float,i:Float,n:Boolean,e:Float){lightAngle=norm(a);pitch=p.coerceIn(-90f,90f);roll=r.coerceIn(-90f,90f);intensity=i.coerceIn(.12f,1f);night=n;elevation=e.coerceIn(-10f,90f);postInvalidateOnAnimation()}
 override fun onDraw(c:Canvas){val w=width.toFloat();val h=height.toFloat();if(w<=0||h<=0)return;val cx=w*.5f;val cy=h*.5f;val r=min(w,h)*.455f;val press=if(isPressed).93f else 1f;c.save();c.scale(press,press,cx,cy);facets(c,cx,cy,r);edges(c,cx,cy,r);c.restore();/* ceinture toujours désactivée pendant le test */}
 private fun facets(c:Canvas,cx:Float,cy:Float,r:Float){val tr=r*.28f;val cr=r*.63f;val gr=r*.96f;for(i in 0 until SEGMENTS){val a0=angle(i);val a1=angle(i+1);facet(c,center(cx,cy,pt(cx,cy,tr,a0),pt(cx,cy,tr,a1)),i,i,(a0+a1)*.5f,0)};for(i in 0 until SEGMENTS){val a0=angle(i);val a1=angle(i+1);val am=(a0+a1)*.5f;val i0=pt(cx,cy,tr,a0);val i1=pt(cx,cy,tr,a1);val m0=pt(cx,cy,cr,a0);val m1=pt(cx,cy,cr,a1);val mm=pt(cx,cy,cr,am);facet(c,poly(i0,m0,mm,i1),16+i*2,i+3,(a0+am)*.5f,1);facet(c,poly(i1,mm,m1),17+i*2,i+9,(am+a1)*.5f,1)};for(i in 0 until SEGMENTS){val a0=angle(i);val a1=angle(i+1);val am=(a0+a1)*.5f;val m0=pt(cx,cy,cr,a0);val m1=pt(cx,cy,cr,a1);val o0=pt(cx,cy,gr,a0);val o1=pt(cx,cy,gr,a1);val om=pt(cx,cy,gr,am);facet(c,poly(m0,o0,om,m1),48+i*2,i+5,(a0+am)*.5f,2);facet(c,poly(m1,om,o1),49+i*2,i+12,(am+a1)*.5f,2)}}
 private fun facet(c:Canvas,path:Path,id:Int,paletteIndex:Int,az:Float,ring:Int){
  val baseTilt=when(ring){0->11f;1->30f;else->47f};val cutVariation=(((paletteIndex*37+ring*53)%17)-8)*.46f;val azVariation=(((paletteIndex*29+ring*11)%13)-6)*.42f;val facetAz=az+azVariation;val facetTilt=baseTilt+cutVariation
  val state=states[id]?:FacetState(diamondPalette()[paletteIndex%diamondPalette().size],referenceAlpha(id,ring,facetTilt)).also{states[id]=it};val sun=sunVectorInPhoneSpace(lightAngle,elevation,pitch,roll);val normal=facetNormal(facetAz,facetTilt)
  val direct=max(0f,dot(normal,sun));val oppositeNormal=facetNormal(facetAz+180f,facetTilt);val oppositeInput=max(0f,dot(oppositeNormal,sun));val centerReturn=(oppositeInput*.82f + direct*.18f).coerceIn(0f,1f);val internal=(centerReturn*(.78f+.22f*normal[2])).coerceIn(0f,1f)
  val view=max(.001f,normal[2]);val half=normalize3(floatArrayOf(sun[0],sun[1],sun[2]+1f));val spec=max(0f,dot(normal,half)).pow(if(night)58f else 105f)*intensity
  state.lastIncidence=direct;state.lastInternal=internal;state.lastSpecular=spec;val base=state.color
  val energy=(direct*.52f+internal*.92f).coerceIn(0f,1.35f);val solarLum=(.94f+energy*.48f*intensity+view*.05f).coerceIn(.92f,1.48f);val lit=Color.rgb((Color.red(base)*solarLum).roundToInt().coerceIn(0,255),(Color.green(base)*solarLum).roundToInt().coerceIn(0,255),(Color.blue(base)*solarLum).roundToInt().coerceIn(0,255))
  val reflected=mix(lit,diamondHighlight(),(internal*.28f+spec*.22f).coerceIn(0f,.34f));val dynamicAlpha=(state.alpha+(energy-.45f)*8f).roundToInt().coerceIn(158,176)
  val q=Math.toRadians((facetAz+90f).toDouble());val gx=cos(q).toFloat()*width*.32f;val gy=sin(q).toFloat()*height*.32f;val inner=mix(base,diamondHighlight(),(internal*.34f).coerceIn(0f,.34f));fill.shader=LinearGradient(width*.5f-gx,height*.5f-gy,width*.5f+gx,height*.5f+gy,alpha(reflected,dynamicAlpha),alpha(inner,(dynamicAlpha*1.02f).roundToInt().coerceAtMost(180)),Shader.TileMode.CLAMP);c.drawPath(path,fill);fill.shader=null
  val lightAlpha=((direct*.48f+internal*.92f)*intensity*LIGHT_ALPHA_MAX).roundToInt().coerceIn(0,LIGHT_ALPHA_MAX);if(lightAlpha>0){fill.color=alpha(mix(base,diamondHighlight(),(.58f+internal*.20f).coerceIn(0f,.78f)),lightAlpha);c.drawPath(path,fill)}
  if(spec>.48f){fill.color=alpha(Color.WHITE,((spec-.48f)/.52f*42f).roundToInt().coerceIn(0,42));c.drawPath(path,fill)}
 }
 private fun referenceAlpha(id:Int,ring:Int,tilt:Float):Int{val signature=((id*13+ring*17)%7)-3;val cut=(((tilt-35f)/35f)*5f).roundToInt();return(BASE_ALPHA+signature+cut).coerceIn(158,174)}
 private fun sunVectorInPhoneSpace(azimuth:Float,elev:Float,pitchDeg:Float,rollDeg:Float):FloatArray{val az=Math.toRadians(azimuth.toDouble());val el=Math.toRadians(elev.toDouble());var x=(cos(az)*cos(el)).toFloat();var y=(sin(az)*cos(el)).toFloat();var z=sin(el).toFloat();val pr=Math.toRadians((-pitchDeg).toDouble());val cp=cos(pr).toFloat();val sp=sin(pr).toFloat();val y1=y*cp-z*sp;val z1=y*sp+z*cp;y=y1;z=z1;val rr=Math.toRadians((-rollDeg).toDouble());val cr=cos(rr).toFloat();val sr=sin(rr).toFloat();val x1=x*cr+z*sr;val z2=-x*sr+z*cr;x=x1;z=z2;return normalize3(floatArrayOf(x,y,z))};private fun facetNormal(azimuth:Float,tilt:Float):FloatArray{val a=Math.toRadians(azimuth.toDouble());val t=Math.toRadians(tilt.toDouble());val s=sin(t).toFloat();return normalize3(floatArrayOf(cos(a).toFloat()*s,sin(a).toFloat()*s,cos(t).toFloat()))}
 private fun edges(c:Canvas,cx:Float,cy:Float,r:Float){edge.strokeWidth=max(1f,r*.007f);edge.color=alpha(diamondHighlight(),32);for(i in 0 until SEGMENTS){val a=angle(i);val p1=pt(cx,cy,r*.28f,a);val p2=pt(cx,cy,r*.63f,a);val p3=pt(cx,cy,r*.96f,a);c.drawLine(cx,cy,p1[0],p1[1],edge);c.drawLine(p1[0],p1[1],p2[0],p2[1],edge);c.drawLine(p2[0],p2[1],p3[0],p3[1],edge)}}
 private fun girdle(c:Canvas,cx:Float,cy:Float,r:Float){edge.style=Paint.Style.STROKE;edge.strokeWidth=max(1.5f,r*.035f);edge.color=alpha(diamondTint(),105);c.drawCircle(cx,cy,r*.982f,edge);edge.strokeWidth=max(1f,r*.009f);edge.color=alpha(diamondHighlight(),70);c.drawCircle(cx,cy,r*.958f,edge)}
 private fun dot(a:FloatArray,b:FloatArray)=a[0]*b[0]+a[1]*b[1]+a[2]*b[2];private fun normalize3(v:FloatArray):FloatArray{val l=sqrt((v[0]*v[0]+v[1]*v[1]+v[2]*v[2]).coerceAtLeast(1e-8f));return floatArrayOf(v[0]/l,v[1]/l,v[2]/l)};private fun angle(i:Int)=-90f+i*(360f/SEGMENTS);private fun norm(v:Float)=((v%360f)+360f)%360f;private fun pt(cx:Float,cy:Float,r:Float,d:Float):FloatArray{val q=Math.toRadians(d.toDouble());return floatArrayOf(cx+cos(q).toFloat()*r,cy+sin(q).toFloat()*r)};private fun poly(vararg p:FloatArray)=Path().apply{moveTo(p[0][0],p[0][1]);for(i in 1 until p.size)lineTo(p[i][0],p[i][1]);close()};private fun center(cx:Float,cy:Float,vararg p:FloatArray)=Path().apply{moveTo(cx,cy);p.forEach{lineTo(it[0],it[1])};close()};private fun alpha(c:Int,a:Int)=Color.argb(a.coerceIn(0,255),Color.red(c),Color.green(c),Color.blue(c));private fun mix(a:Int,b:Int,t:Float):Int{val q=t.coerceIn(0f,1f);return Color.rgb((Color.red(a)+(Color.red(b)-Color.red(a))*q).roundToInt().coerceIn(0,255),(Color.green(a)+(Color.green(b)-Color.green(a))*q).roundToInt().coerceIn(0,255),(Color.blue(a)+(Color.blue(b)-Color.blue(a))*q).roundToInt().coerceIn(0,255))}
}
