package com.amaury.pointage

import android.content.Context
import android.graphics.*
import android.util.AttributeSet
import android.widget.Button
import java.util.Collections
import java.util.WeakHashMap
import kotlin.math.*

open class RedDiamondFinalButton @JvmOverloads constructor(context:Context,attrs:AttributeSet?=null,defStyleAttr:Int=android.R.attr.buttonStyle):Button(context,attrs,defStyleAttr){
 companion object{const val RENDER_NAME="Diamant rouge final";private const val FACETS=16;private const val N_AIR=1.000293f;private const val N_DIAMOND=2.417f;private val live=Collections.newSetFromMap(WeakHashMap<RedDiamondFinalButton,Boolean>());fun updateGlobalNaturalLight(angle:Float,pitch:Float,roll:Float,intensity:Float,night:Boolean,elevation:Float){live.toList().forEach{it.setNaturalLight(angle,pitch,roll,intensity,night,elevation)}}}
 private val fill=Paint(Paint.ANTI_ALIAS_FLAG);private val edge=Paint(Paint.ANTI_ALIAS_FLAG).apply{style=Paint.Style.STROKE};private val glow=Paint(Paint.ANTI_ALIAS_FLAG);private val outer=Path();private var lightAngle=-55f;private var pitch=0f;private var roll=0f;private var intensity=.78f;private var night=false;private var elevation=45f
 open fun diamondPalette()=intArrayOf(Color.rgb(255,50,76),Color.rgb(214,5,35),Color.rgb(132,0,24),Color.rgb(255,92,118),Color.rgb(92,0,20),Color.rgb(238,12,48),Color.rgb(178,0,31),Color.rgb(255,148,164),Color.rgb(110,0,25),Color.rgb(245,22,56),Color.rgb(156,0,29),Color.rgb(255,72,102),Color.rgb(74,0,18),Color.rgb(226,8,42),Color.rgb(194,0,34),Color.rgb(255,118,140));open fun diamondTint()=Color.rgb(255,28,62);open fun diamondDark()=Color.rgb(96,0,22);open fun diamondHighlight()=Color.rgb(255,238,243)
 init{background=null;stateListAnimator=null;setPadding(0,0,0,0);isAllCaps=false} override fun onAttachedToWindow(){super.onAttachedToWindow();live.add(this)} override fun onDetachedFromWindow(){live.remove(this);super.onDetachedFromWindow()} fun setDiamondLightAngle(a:Float)=setNaturalLight(a,pitch,roll,intensity,night,elevation) private fun setNaturalLight(a:Float,p:Float,r:Float,i:Float,n:Boolean,e:Float){lightAngle=norm(a);pitch=p.coerceIn(-90f,90f);roll=r.coerceIn(-90f,90f);intensity=i.coerceIn(.12f,1f);night=n;elevation=e.coerceIn(-10f,90f);invalidate()}
 override fun onDraw(c:Canvas){val w=width.toFloat();val h=height.toFloat();if(w<=0||h<=0)return;val cx=w*.5f;val cy=h*.5f;val r=min(w,h)*.465f;val press=if(isPressed).93f else 1f;c.save();c.scale(press,press,cx,cy);outer.reset();outer.addCircle(cx,cy,r,Path.Direction.CW);c.clipPath(outer);drawGlass(c,cx,cy,r);drawFacets(c,cx,cy,r);drawEdges(c,cx,cy,r);drawCausticGlints(c,cx,cy,r);c.restore();drawRim(c,cx,cy,r*press)}
 private fun drawGlass(c:Canvas,cx:Float,cy:Float,r:Float){val q=Math.toRadians(lightAngle.toDouble());val lx=cx+cos(q).toFloat()*r*.22f;val ly=cy+sin(q).toFloat()*r*.22f;val t=diamondTint();val d=diamondDark();val amb=if(night).55f else .76f;fill.shader=RadialGradient(lx,ly,r*1.3f,intArrayOf(alpha(lighten(t,.31f),(166+62*intensity).toInt()),alpha(t,(186+48*amb).toInt()),alpha(d,216),Color.argb(232,Color.red(d)/6,Color.green(d)/6,Color.blue(d)/6)),floatArrayOf(0f,.34f,.72f,1f),Shader.TileMode.CLAMP);c.drawCircle(cx,cy,r,fill);fill.shader=null}
 private fun drawFacets(c:Canvas,cx:Float,cy:Float,r:Float){val ir=r*.30f;val mr=r*.64f;val orr=r*.96f;for(i in 0 until FACETS){val a0=angle(i);val a1=angle(i+1);facet(c,center(cx,cy,pt(cx,cy,ir,a0),pt(cx,cy,ir,a1)),i,(a0+a1)*.5f,0,1.10f)};for(i in 0 until FACETS){val a0=angle(i);val a1=angle(i+1);val am=(a0+a1)*.5f;val i0=pt(cx,cy,ir,a0);val i1=pt(cx,cy,ir,a1);val m0=pt(cx,cy,mr,a0);val m1=pt(cx,cy,mr,a1);val mm=pt(cx,cy,mr,am);facet(c,poly(i0,m0,mm,i1),i+3,(a0+am)*.5f,1,.92f);facet(c,poly(i1,mm,m1),i+9,(am+a1)*.5f,1,.82f)};for(i in 0 until FACETS){val a0=angle(i);val a1=angle(i+1);val am=(a0+a1)*.5f;val m0=pt(cx,cy,mr,a0);val m1=pt(cx,cy,mr,a1);val o0=pt(cx,cy,orr,a0);val o1=pt(cx,cy,orr,a1);val om=pt(cx,cy,orr,am);facet(c,poly(m0,o0,om,m1),i+5,(a0+am)*.5f,2,.74f);facet(c,poly(m1,om,o1),i+12,(am+a1)*.5f,2,.64f)}}
 private fun facet(c:Canvas,path:Path,index:Int,azimuth:Float,ring:Int,energy:Float){val nt=when(ring){0->18f;1->31f;else->43f}+(((index*37+ring*53)%17)-8)*.42f;val na=azimuth+(((index*29+ring*11)%13)-6)*.38f;val N=normal3(na,nt,pitch,roll);val L=light3(lightAngle,elevation);val V=floatArrayOf(0f,0f,1f);val ndl=max(0f,dot(N,L));val ndv=max(.001f,dot(N,V));val H=normalize3(floatArrayOf(L[0]+V[0],L[1]+V[1],L[2]+V[2]));val ndh=max(0f,dot(N,H));val r0=((N_AIR-N_DIAMOND)/(N_AIR+N_DIAMOND)).pow(2);val fresnel=r0+(1-r0)*(1-ndv).pow(5);val spec=ndh.pow(if(night)72f else 145f)*intensity;val inc=Math.toDegrees(acos(ndl.coerceIn(0f,1f)).toDouble()).toFloat();val critical=Math.toDegrees(asin((N_AIR/N_DIAMOND).toDouble())).toFloat();val tir=if(inc>critical)((inc-critical)/(90-critical)).coerceIn(0f,1f) else 0f;val transmission=(1-fresnel)*(1-tir)*ndl;val brightness=(.11f+energy*(ndl*.62f+transmission*.34f)+fresnel*.24f).coerceIn(.08f,1.35f)*(.62f+.48f*intensity);val base=diamondPalette()[index%diamondPalette().size];val hi=diamondHighlight();val rr=(Color.red(base)*brightness).toInt().coerceIn(0,255);val gg=(Color.green(base)*brightness).toInt().coerceIn(0,255);val bb=(Color.blue(base)*brightness).toInt().coerceIn(0,255);val flash=(spec*1.9f+fresnel*.18f+tir*.22f).coerceIn(0f,1f);val top=mix(Color.rgb(rr,gg,bb),hi,flash);val deep=Color.rgb((rr*.32f).toInt(),(gg*.32f).toInt(),(bb*.32f).toInt());val a=(150+ndl*58+fresnel*30).toInt().coerceIn(145,244);fill.shader=LinearGradient(0f,0f,width.toFloat(),height.toFloat(),alpha(top,a),alpha(deep,(a*.70f).toInt()),Shader.TileMode.CLAMP);c.drawPath(path,fill);fill.shader=null;if(spec>.38f){fill.color=alpha(Color.WHITE,((spec-.38f)/.62f*185).toInt().coerceIn(0,185));c.drawPath(path,fill)};drawFacetFire(c,path,index,ring,ndh,transmission,tir)}
 /* Feu discret: jamais un voile RGB global. Il n'apparait que dans quelques facettes lorsque l'alignement optique est favorable. */
 private fun drawFacetFire(c:Canvas,path:Path,index:Int,ring:Int,alignment:Float,transmission:Float,tir:Float){if(night)return;val threshold=.885f+ring*.018f;val gate=((alignment-threshold)/(1-threshold)).coerceIn(0f,1f);val selector=((index*17+ring*7)%11)/10f;val rarity=if(selector>.38f)0f else 1f;if(gate<=0f||rarity==0f)return;val power=(gate.pow(1.8f)*transmission*(.35f+.65f*intensity)*(1-.35f*tir)).coerceIn(0f,.34f);if(power<.018f)return;val q=Math.toRadians((lightAngle+index*3.7f).toDouble());val dx=cos(q).toFloat()*width*.010f;val dy=sin(q).toFloat()*height*.010f;val warm=Color.rgb(255,126,48);val cool=Color.rgb(92,154,255);fill.shader=LinearGradient(width*.5f-dx,height*.5f-dy,width*.5f+dx,height*.5f+dy,intArrayOf(alpha(warm,(92*power).toInt()),Color.TRANSPARENT,alpha(cool,(104*power).toInt())),floatArrayOf(0f,.50f,1f),Shader.TileMode.CLAMP);c.drawPath(path,fill);fill.shader=null}
 private fun drawEdges(c:Canvas,cx:Float,cy:Float,r:Float){val hi=diamondHighlight();edge.strokeWidth=maxOf(1f,r*.009f);edge.color=alpha(hi,if(night)48 else 78);for(i in 0 until FACETS){val a=angle(i);val p1=pt(cx,cy,r*.30f,a);val p2=pt(cx,cy,r*.64f,a);val p3=pt(cx,cy,r*.96f,a);c.drawLine(cx,cy,p1[0],p1[1],edge);c.drawLine(p1[0],p1[1],p2[0],p2[1],edge);c.drawLine(p2[0],p2[1],p3[0],p3[1],edge)};edge.alpha=54;c.drawCircle(cx,cy,r*.30f,edge);c.drawCircle(cx,cy,r*.64f,edge);edge.alpha=255}
 private fun drawCausticGlints(c:Canvas,cx:Float,cy:Float,r:Float){val q=Math.toRadians(lightAngle.toDouble());val ux=cos(q).toFloat();val uy=sin(q).toFloat();val hi=diamondHighlight();val ef=((elevation+5)/70).coerceIn(.15f,1f);val power=intensity*ef*(if(night).38f else 1f);val x=cx+ux*r*(.45f+roll*.0015f).coerceIn(.28f,.66f);val y=cy+uy*r*(.45f-pitch*.0015f).coerceIn(.28f,.66f);glow.shader=RadialGradient(x,y,r*.26f,intArrayOf(alpha(Color.WHITE,(238*power).toInt().coerceIn(18,238)),alpha(hi,(130*power).toInt().coerceIn(10,130)),alpha(diamondTint(),(30*power).toInt()),Color.TRANSPARENT),floatArrayOf(0f,.08f,.34f,1f),Shader.TileMode.CLAMP);c.drawCircle(x,y,r*.26f,glow);glow.shader=null;if(!night&&power>.42f){edge.strokeWidth=maxOf(1f,r*.012f);edge.color=alpha(Color.WHITE,(225*power).toInt().coerceIn(45,225));val len=r*(.055f+.15f*power);c.drawLine(x-len,y,x+len,y,edge);c.drawLine(x,y-len,x,y+len,edge)}}
 private fun drawRim(c:Canvas,cx:Float,cy:Float,r:Float){val d=diamondDark();val t=diamondTint();val hi=diamondHighlight();edge.style=Paint.Style.STROKE;edge.strokeWidth=maxOf(1.2f,r*.026f);edge.shader=SweepGradient(cx,cy,intArrayOf(d,hi,t,d,hi,t,d),null);c.drawCircle(cx,cy,r,edge);edge.shader=null}
 private fun normal3(az:Float,tilt:Float,p:Float,r:Float):FloatArray{val ar=Math.toRadians((az+r*.18f).toDouble());val tr=Math.toRadians((tilt+p*.08f).coerceIn(2f,82f).toDouble());val s=sin(tr).toFloat();return normalize3(floatArrayOf(cos(ar).toFloat()*s,sin(ar).toFloat()*s,cos(tr).toFloat()))} private fun light3(az:Float,e:Float):FloatArray{val ar=Math.toRadians(az.toDouble());val er=Math.toRadians(e.coerceIn(-5f,90f).toDouble());val ce=cos(er).toFloat();return normalize3(floatArrayOf(cos(ar).toFloat()*ce,sin(ar).toFloat()*ce,sin(er).toFloat()))} private fun dot(a:FloatArray,b:FloatArray)=a[0]*b[0]+a[1]*b[1]+a[2]*b[2] private fun normalize3(v:FloatArray):FloatArray{val l=sqrt((v[0]*v[0]+v[1]*v[1]+v[2]*v[2]).coerceAtLeast(1e-8f));return floatArrayOf(v[0]/l,v[1]/l,v[2]/l)} private fun angle(i:Int)=-90f+i*(360f/FACETS);private fun norm(v:Float)=((v%360)+360)%360 private fun pt(cx:Float,cy:Float,r:Float,d:Float):FloatArray{val q=Math.toRadians(d.toDouble());return floatArrayOf(cx+cos(q).toFloat()*r,cy+sin(q).toFloat()*r)} private fun poly(vararg p:FloatArray)=Path().apply{moveTo(p[0][0],p[0][1]);for(i in 1 until p.size)lineTo(p[i][0],p[i][1]);close()} private fun center(cx:Float,cy:Float,vararg p:FloatArray)=Path().apply{moveTo(cx,cy);p.forEach{lineTo(it[0],it[1])};close()} private fun alpha(c:Int,a:Int)=Color.argb(a.coerceIn(0,255),Color.red(c),Color.green(c),Color.blue(c)) private fun lighten(c:Int,t:Float)=Color.rgb((Color.red(c)+(255-Color.red(c))*t).toInt(),(Color.green(c)+(255-Color.green(c))*t).toInt(),(Color.blue(c)+(255-Color.blue(c))*t).toInt()) private fun mix(a:Int,b:Int,t:Float):Int{val q=t.coerceIn(0f,1f);return Color.rgb((Color.red(a)+(Color.red(b)-Color.red(a))*q).toInt(),(Color.green(a)+(Color.green(b)-Color.green(a))*q).toInt(),(Color.blue(a)+(Color.blue(b)-Color.blue(a))*q).toInt())}
}