package com.amaury.pointage

import android.app.Activity
import android.app.AlertDialog
import android.content.Context
import android.content.Intent
import android.graphics.Typeface
import android.net.Uri
import android.view.GestureDetector
import android.view.Gravity
import android.view.MotionEvent
import android.view.ViewGroup
import android.widget.Button
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import com.amaury.pointage.v2.HoraTrackV2
import com.amaury.pointage.v2.V2PayslipStore
import com.amaury.pointage.v2.V2RuntimeStore
import com.amaury.pointage.v2.engine.CompanyAgreementPayrollBridgeV2
import com.amaury.pointage.v2.engine.CompanyPayrollOverridesV2
import com.amaury.pointage.v2.engine.ConventionPayrollReferenceV2
import com.amaury.pointage.v2.engine.NetSalaryEngineV2
import com.amaury.pointage.v2.engine.PayrollPeriodV2
import java.text.DateFormatSymbols
import java.text.SimpleDateFormat
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.temporal.ChronoUnit
import java.util.Calendar
import java.util.Locale
import kotlin.math.abs

/** Espace V2 : estimation HoraTrack + nombre illimité de bulletins réels. */
class SalaryPayslipWorkspaceView(context:Context,private val company:SalaryCompanyStore.Company):LinearLayout(context){
 private var page=0
 private val pageBox=LinearLayout(context)
 private val indicator=TextView(context)
 private val gesture=GestureDetector(context,object:GestureDetector.SimpleOnGestureListener(){override fun onDown(e:MotionEvent)=true;override fun onFling(e1:MotionEvent?,e2:MotionEvent,velocityX:Float,velocityY:Float):Boolean{if(e1==null||abs(e2.x-e1.x)<80)return false;if(e2.x<e1.x)next() else previous();return true}})
 init{orientation=VERTICAL;setPadding(dp(12),dp(8),dp(12),dp(12));addView(TextView(context).apply{text="FICHE DE SALAIRE";textSize=18f;setTypeface(typeface,Typeface.BOLD);gravity=Gravity.CENTER});addView(TextView(context).apply{text="L’estimation utilise le moteur V2 et les données de cette entreprise uniquement.";textSize=12f;setPadding(0,dp(5),0,dp(8))});addButtonTop("CHOISIR LE MOIS"){choosePeriod()};pageBox.orientation=VERTICAL;pageBox.setOnTouchListener{_,e->gesture.onTouchEvent(e)};addView(pageBox,LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));indicator.gravity=Gravity.CENTER;indicator.textSize=14f;indicator.setPadding(0,dp(8),0,dp(8));indicator.setOnClickListener{choosePage()};addView(indicator);render()}
 private fun records()=V2PayslipStore.forCompany(context,company.id)
 private fun render(){val total=records().size+1;page=page.coerceIn(0,total-1);pageBox.removeAllViews();if(page==0)renderEstimate() else renderReal(records()[page-1]);indicator.text="${page+1} / $total"}
 private fun selectedPeriod():Pair<Int,Int>{val ms=context.getSharedPreferences("navigation_state",Context.MODE_PRIVATE).getLong("report_month_ms",-1L);val c=Calendar.getInstance(Locale.FRANCE);if(ms>0)c.timeInMillis=ms;return c.get(Calendar.YEAR) to c.get(Calendar.MONTH)}
 private fun choosePeriod(){val labels=ArrayList<String>();val values=ArrayList<Long>();val c=Calendar.getInstance(Locale.FRANCE).apply{set(Calendar.DAY_OF_MONTH,1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};repeat(36){labels+=SimpleDateFormat("MMMM yyyy",Locale.FRANCE).format(c.time).replaceFirstChar{it.uppercase()};values+=c.timeInMillis;c.add(Calendar.MONTH,-1)};AlertDialog.Builder(context).setTitle("Choisir le mois").setItems(labels.toTypedArray()){_,which->context.getSharedPreferences("navigation_state",Context.MODE_PRIVATE).edit().putLong("report_month_ms",values[which]).apply();render()}.setNegativeButton("ANNULER",null).show()}
 private fun renderEstimate(){
  val prefs=SalaryCompanyStore.prefs(context,company.id);val weekly=prefs.getString("contract_weekly_hours","").orEmpty();val mealRaw=prefs.getString("meal_amount","").orEmpty();val(year,month)=selectedPeriod();val period=SimpleDateFormat("MMMM yyyy",Locale.FRANCE).format(Calendar.getInstance(Locale.FRANCE).apply{set(year,month,1)}.time).replaceFirstChar{it.uppercase()}
  add(TextView(context).apply{text="FICHE DE PAIE ESTIMATIVE";textSize=17f;setTypeface(typeface,Typeface.BOLD);gravity=Gravity.CENTER;setPadding(0,dp(10),0,dp(4))})
  val seniority=seniority(prefs.getString("entry_date","").orEmpty(),year,month);add(TextView(context).apply{text="Période : $period\nEntreprise : ${company.name.ifBlank{"Non renseignée"}}\nSIRET : ${company.siret.ifBlank{"Non renseigné"}}\nAncienneté : $seniority";textSize=14f;setPadding(0,0,0,dp(10))})
  val conventionId=company.idcc.ifBlank{prefs.getString("company_idcc","").orEmpty()};val convention=ConventionCatalog.findByIdcc(context,conventionId);val calc=if(HoraTrackV2.ENABLED&&convention!=null)runCatching{V2SalaryAdapter.calculateForCompany(context,company,year,month,convention)}.getOrNull() else null
  if(calc==null){add(TextView(context).apply{text="Calcul détaillé indisponible : complète le contrat et la convention de cette entreprise. HoraTrack n’invente aucune majoration.";textSize=14f})}else{
   val mealAmount=mealRaw.replace(',','.').toDoubleOrNull()?.coerceAtLeast(0.0)?:0.0;val mealCount=countMeals(year,month);val mealTotal=mealCount*mealAmount;val payrollPeriod=PayrollPeriodV2.month(year,month);val referenceDate=payrollPeriod.referenceDate;val payroll=NetSalaryEngineV2.calculate(calc.monthlyEstimatedGross,year,CompanyPayrollOverridesV2.load(context,company.id,referenceDate));val agreementRules=CompanyAgreementPayrollBridgeV2.load(context,company.id,referenceDate,payrollPeriod)
   val coefficient=prefs.getString("convention_coefficient","").orEmpty().trim().toIntOrNull();val conventionMinimum=coefficient?.let{ConventionPayrollReferenceV2.minimum(conventionId.filter(Char::isDigit).trimStart('0'),referenceDate,it)}
   val lines=buildString{append("Convention : ").append(convention?.displayName?:"Non renseignée").append('\n');if(coefficient!=null)append("Coefficient : ").append(coefficient).append('\n');if(conventionMinimum!=null)append("Minimum conventionnel mensuel : ").append(eur(conventionMinimum.monthlyGross)).append(" (base 151,67 h)\n");append("Heures normales : ").append(hours(calc.regularMs)).append(" — ").append(eur(calc.regularGross)).append('\n');calc.overtimeTiers.filter{it.durationMs>0}.forEach{append(it.label).append(" : ").append(hours(it.durationMs)).append('\n')};append("Heures de nuit : ").append(hours(calc.nightMs)).append('\n');append("Samedi : ").append(hours(calc.saturdayMs)).append('\n');append("Dimanche : ").append(hours(calc.sundayMs)).append('\n');append("Majoration / primes calculées : ").append(eur(calc.premiumsGross)).append('\n');append("Paniers : ").append(mealCount).append(" × ").append(eur(mealAmount)).append(" = ").append(eur(mealTotal)).append('\n');append("BRUT ESTIMÉ HORS PANIERS : ").append(eur(calc.monthlyEstimatedGross)).append('\n');append("BRUT + PANIERS : ").append(eur(calc.monthlyEstimatedGross+mealTotal)).append('\n');append("\nCOTISATIONS LÉGALES : -").append(eur(payroll.statutory)).append('\n');append("RETRAITE COMPLÉMENTAIRE AGIRC-ARRCO / CEG / CET : -").append(eur(payroll.complementaryRetirement)).append('\n');if(payroll.companyEmployeeDeductions>0)append("RETENUES ENTREPRISE/SALARIÉ CONNUES : -").append(eur(payroll.companyEmployeeDeductions)).append('\n');append("NET ESTIMÉ AVANT IMPÔT : ").append(eur(payroll.netBeforeIncomeTax)).append('\n');payroll.netTaxable?.let{append("NET IMPOSABLE ESTIMÉ : ").append(eur(it)).append('\n')};payroll.incomeTax?.let{append("PRÉLÈVEMENT À LA SOURCE : -").append(eur(it)).append('\n')};payroll.netAfterIncomeTax?.let{append("NET ESTIMÉ APRÈS PAS : ").append(eur(it)).append('\n')}}
   add(TextView(context).apply{text=lines;textSize=14f});if(agreementRules.hasApplicableRules)add(TextView(context).apply{text="\nRÈGLES D’ENTREPRISE APPLICABLES — information uniquement\n• "+agreementRules.applicableRules.joinToString("\n• "){"${it.category.name} : ${it.excerpt}"}+"\nAucune de ces règles ne modifie encore automatiquement le calcul.";textSize=12f});if(agreementRules.hasOvertimeConflicts)add(TextView(context).apply{text="\n⚠ CONFLIT D’HEURES SUPPLÉMENTAIRES — BLOQUÉ\n"+agreementRules.conflictingOvertimeRules.joinToString("\n"){rule->val end=rule.band.toHourInclusive?.let{"${it}e heure"}?:"sans limite déterminée";"• ${rule.band.fromHourInclusive}e → $end : +${String.format(Locale.FRANCE,"%.2f",rule.percent)} %\n  ${rule.source.source.excerpt}"}+"\nCes règles restent enregistrées mais sont exclues du calcul tant que le conflit n’est pas résolu.";textSize=12f;setTypeface(typeface,Typeface.BOLD)});ConventionNightRules.forIdcc(convention?.idcc.orEmpty())?.let{rule->add(TextView(context).apply{text="\nRègle nuit : ${rule.note}";textSize=12f})};val conventionWarnings=mutableListOf<String>();if(conventionId.filter(Char::isDigit).trimStart('0')=="292"){if(coefficient==null)conventionWarnings+="Coefficient conventionnel manquant : minimum IDCC 292 non contrôlable." else if(conventionMinimum==null)conventionWarnings+="Aucun minimum conventionnel daté trouvé pour le coefficient $coefficient et cette période." else if(calc.regularGross+1e-6<conventionMinimum.monthlyGross)conventionWarnings+="Salaire de base estimé inférieur au minimum conventionnel indicatif : vérifier l’assiette de comparaison avant conclusion."};val warnings=calc.warnings+payroll.warnings+conventionWarnings;if(warnings.isNotEmpty())add(TextView(context).apply{text="\nÀ vérifier :\n• "+warnings.distinct().joinToString("\n• ");textSize=12f})
  }
  add(TextView(context).apply{text="\nDurée hebdomadaire contractuelle : ${weekly.ifBlank{"à compléter"}}\nCette fiche est une estimation HoraTrack, pas un bulletin officiel.";textSize=12f});addButton("PRENDRE UNE PHOTO"){launchPhoto()};addButton("IMPORTER UN FICHIER"){launchImport()}
 }
 private fun countMeals(year:Int,month:Int):Int{val aliases=SalaryCompanyStore.acceptedEmployerIds(context,company.id);val firstByDay=linkedMapOf<String,Long>();val day=SimpleDateFormat("yyyy-MM-dd",Locale.FRANCE);V2RuntimeStore.allSessions(context).forEach{s->val entry=s.countedEntryMs?:s.realArrivalMs?:return@forEach;if(s.realExitMs==null||s.employerId !in aliases)return@forEach;val c=Calendar.getInstance(Locale.FRANCE).apply{timeInMillis=entry};if(c.get(Calendar.YEAR)!=year||c.get(Calendar.MONTH)!=month)return@forEach;val key=day.format(c.time);val old=firstByDay[key];if(old==null||entry<old)firstByDay[key]=entry};return firstByDay.values.count{entry->ShiftProfileManager.mealEnabled(context,ShiftProfileManager.detect(entry))}}
 private fun seniority(raw:String,year:Int,month:Int):String{val start=runCatching{LocalDate.parse(raw.trim(),DateTimeFormatter.ofPattern("dd/MM/yyyy",Locale.FRANCE))}.getOrNull()?:return "à compléter";val end=LocalDate.of(year,month+1,1).withDayOfMonth(LocalDate.of(year,month+1,1).lengthOfMonth());if(start.isAfter(end))return "0 mois";val months=ChronoUnit.MONTHS.between(start.withDayOfMonth(1),end.withDayOfMonth(1)).toInt();val y=months/12;val m=months%12;return when{y>0&&m>0->"$y an${if(y>1)"s" else ""} et $m mois";y>0->"$y an${if(y>1)"s" else ""}";else->"$m mois"}}
 private fun renderReal(r:V2PayslipStore.Record){val month=DateFormatSymbols(Locale.FRANCE).months.getOrNull(r.month).orEmpty().replaceFirstChar{it.uppercase()};val gross=r.gross?.let{eur(it)}?:"à confirmer";val net=r.net?.let{eur(it)}?:"non renseigné";add(TextView(context).apply{text="BULLETIN RÉEL — $month ${r.year}";textSize=17f;setTypeface(typeface,Typeface.BOLD);gravity=Gravity.CENTER;setPadding(0,dp(10),0,dp(10))});add(TextView(context).apply{text="Brut : $gross\nNet : $net\nDocument original conservé.";textSize=14f});addButton("OUVRIR LE DOCUMENT"){val uri=Uri.parse(r.sourceUri);runCatching{context.startActivity(Intent(Intent.ACTION_VIEW).apply{setDataAndType(uri,r.sourceMime?:"*/*");addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)})}.onFailure{Toast.makeText(context,"Impossible d’ouvrir le document",Toast.LENGTH_LONG).show()}};addButton("ANALYSER / COMPARER AVEC L’IA"){askAiConsent(r)};addButton("SUPPRIMER CE BULLETIN"){AlertDialog.Builder(context).setTitle("Supprimer ce bulletin ?").setMessage("Le bulletin sera retiré de l’historique HoraTrack. Le fichier original extérieur à HoraTrack n’est pas modifié.").setNegativeButton("ANNULER",null).setPositiveButton("SUPPRIMER"){_,_->V2PayslipStore.remove(context,r.id);page=(page-1).coerceAtLeast(0);render()}.show()}}
 private fun launchPhoto(){val a=context as? Activity?:return;a.startActivity(Intent(context,SalaryPayslipPhotoActivity::class.java).putExtra(V2PayslipImportActivity.EXTRA_COMPANY_ID,company.id).putExtra(V2PayslipImportActivity.EXTRA_COMPANY_NAME,company.name))}
 private fun launchImport(){val a=context as? Activity?:return;a.startActivity(Intent(context,V2PayslipImportActivity::class.java).putExtra(V2PayslipImportActivity.EXTRA_COMPANY_ID,company.id).putExtra(V2PayslipImportActivity.EXTRA_COMPANY_NAME,company.name))}
 private fun askAiConsent(r:V2PayslipStore.Record){AlertDialog.Builder(context).setTitle("Analyse avec l’IA").setMessage("Autoriser l’analyse comparative de ce bulletin avec l’estimation HoraTrack ? Les résultats distinguent calcul certain, estimation et anomalie potentielle.").setNegativeButton("ANNULER",null).setPositiveButton("AUTORISER"){_,_->val comparison=V2PayslipStore.comparison(context,r);val message=when{comparison==null->"Comparaison insuffisante : complète les données Salaire/Convention. Aucune conclusion juridique n’est inventée.";comparison.conforming->"Calcul : les montants contrôlés concordent avec l’estimation HoraTrack dans la tolérance du moteur.";else->"Anomalie potentielle : un ou plusieurs écarts sont détectés. Vérification nécessaire avant toute conclusion."};AlertDialog.Builder(context).setTitle("Comparaison").setMessage(message).setPositiveButton("OK",null).show()}.show()}
 private fun next(){if(page<records().size){page++;render()}};private fun previous(){if(page>0){page--;render()}}
 private fun choosePage(){val rs=records();val labels=ArrayList<String>();labels+="Estimation HoraTrack";rs.forEach{r->val m=DateFormatSymbols(Locale.FRANCE).months.getOrNull(r.month).orEmpty().replaceFirstChar{it.uppercase()};labels+="Bulletin réel — $m ${r.year}"};AlertDialog.Builder(context).setTitle("Choisir une page").setItems(labels.toTypedArray()){_,which->page=which;render()}.setNegativeButton("ANNULER",null).show()}
 private fun add(v:android.view.View){pageBox.addView(v)}
 private fun addButtonTop(label:String,click:()->Unit){addView(Button(context).apply{text=label;isAllCaps=false;setBackgroundResource(R.drawable.hp_panel);setOnClickListener{click()}},LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(52)).apply{bottomMargin=dp(7)})}
 private fun addButton(label:String,click:()->Unit){pageBox.addView(Button(context).apply{text=label;isAllCaps=false;setBackgroundResource(R.drawable.hp_panel);setOnClickListener{click()}},LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(52)).apply{topMargin=dp(7)})}
 private fun hours(ms:Long)=String.format(Locale.FRANCE,"%.2f h",ms/3_600_000.0)
 private fun eur(v:Double)=String.format(Locale.FRANCE,"%.2f €",v)
 private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}