package com.amaury.pointage

import android.app.Activity
import android.content.Context
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.text.InputType
import android.util.AttributeSet
import android.view.Gravity
import android.view.View
import android.view.ViewGroup
import android.view.WindowManager
import android.widget.*

class SalaryInformationSheetView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null) : LinearLayout(context, attrs) {
    companion object { const val TAG="salary_information_sheet"; private const val AWAKE_MS=15L*60L*1000L }
    private val theme get()=AppThemeCatalog.current(context); private val dark get()=AppThemeCatalog.useDarkPalette(context)
    private val textColor get()=if(dark)theme.darkText else theme.lightText; private val hintColor get()=if(dark)theme.darkHint else theme.lightHint; private val accentColor get()=if(dark)theme.accentLight else theme.accent; private val panelColor get()=if(dark)theme.darkPanel else theme.lightPanel
    private val companyLabel=TextView(context); private val contractType=Spinner(context)
    private val weeklyHours=field("Durée hebdomadaire contractuelle — ex. 35",InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL)
    private val forfaitHours=field("Nombre d’heures du forfait annuel",InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL)
    private val forfaitDays=field("Nombre de jours du forfait annuel — max. standard 218",InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL)
    private val monthlyGross=field("Salaire brut mensuel convenu",InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL)
    private val hourlyRate=field("Taux horaire brut — ex. 13,70",InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL)
    private val mealAmount=field("Montant du panier — ex. 5,38",InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL)
    private val incomeTaxRate=field("Taux prélèvement à la source (%) — ex. 3,2",InputType.TYPE_CLASS_NUMBER or InputType.TYPE_NUMBER_FLAG_DECIMAL)
    private val entryDate=field("Date d’entrée — JJ/MM/AAAA"); private val status=TextView(context)
    private var selectedCompanyId:String?=null; private var company:SalaryCompanyStore.Company?=null; private val stopAwake=Runnable{clearKeepAwake()}
    init { tag=TAG; orientation=VERTICAL; setPadding(dp(14),dp(14),dp(14),dp(14)); applyPanelBackground(this); buildUi(); refresh() }
    fun bindCompany(companyId:String):SalaryInformationSheetView { selectedCompanyId=companyId; refresh(); return this }
    override fun onAttachedToWindow(){super.onAttachedToWindow();keepAwakeTemporarily()}; override fun onDetachedFromWindow(){removeCallbacks(stopAwake);clearKeepAwake();super.onDetachedFromWindow()}
    fun refresh(){val id=selectedCompanyId;company=if(id.isNullOrBlank())null else SalaryCompanyStore.list(context).firstOrNull{it.id==id};val c=company;companyLabel.text=when{ id.isNullOrBlank()->"Aucune entreprise sélectionnée";c==null->"Entreprise introuvable";c.siret.isBlank()->c.name.ifBlank{"Entreprise"};else->"${c.name.ifBlank{"Entreprise"}}\nSIRET : ${c.siret}"};if(c!=null)loadCompany(c)else clearFields();setFormEnabled(c!=null);applyThemeRecursively(this)}
    private fun buildUi(){
        addView(TextView(context).apply{text="📋 FICHE DE RENSEIGNEMENTS";textSize=17f;setTypeface(typeface,Typeface.BOLD);gravity=Gravity.CENTER});addView(TextView(context).apply{text="Cette fiche appartient uniquement à l’entreprise ouverte.";textSize=13f;setTextColor(hintColor);setPadding(0,dp(7),0,dp(12))})
        addLabel("ENTREPRISE");companyLabel.apply{textSize=14f;setTypeface(typeface,Typeface.BOLD);background=controlBackground();setPadding(dp(12),dp(8),dp(12),dp(8))};addView(companyLabel,rowParams())
        addLabel("CONTRAT");contractType.adapter=themedAdapter(listOf("Choisir le type de contrat","Temps plein","Temps partiel","Forfait heures annuel","Forfait jours annuel","Forfait à préciser (ancien)","Autre"));contractType.background=controlBackground();contractType.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:View?,i:Int,l:Long){updateContractFields()};override fun onNothingSelected(p:AdapterView<*>?){}};addView(contractType,rowParams());addView(entryDate,rowParams());addView(weeklyHours,rowParams());addView(forfaitHours,rowParams());addView(forfaitDays,rowParams())
        addLabel("RÉMUNÉRATION");addView(hourlyRate,rowParams());addView(monthlyGross,rowParams());addView(mealAmount,rowParams());addView(incomeTaxRate,rowParams());status.textSize=13f;status.setPadding(0,dp(10),0,dp(8));addView(status);addView(Button(context).apply{tag="information_sheet_save";text="ENREGISTRER LA FICHE";isAllCaps=false;setTextColor(accentColor);applyPanelBackground(this);setOnClickListener{save()}},LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(54)).apply{topMargin=dp(5)})
    }
    private fun updateContractFields(){val t=contractValue(contractType.selectedItemPosition);weeklyHours.visibility=if(t=="FULL_TIME"||t=="PART_TIME"||t=="OTHER")View.VISIBLE else View.GONE;forfaitHours.visibility=if(t=="FORFAIT_HEURES")View.VISIBLE else View.GONE;forfaitDays.visibility=if(t=="FORFAIT_JOURS")View.VISIBLE else View.GONE;hourlyRate.visibility=if(t=="FORFAIT_JOURS")View.GONE else View.VISIBLE;monthlyGross.visibility=if(t=="FORFAIT_JOURS")View.VISIBLE else View.GONE}
    private fun loadCompany(c:SalaryCompanyStore.Company){val p=SalaryCompanyStore.prefs(context,c.id);contractType.setSelection(contractIndex(p.getString("contract_type","").orEmpty()));weeklyHours.setText(p.getString("contract_weekly_hours","").orEmpty().replace('.',','));forfaitHours.setText(p.getString("forfait_annual_hours","").orEmpty().replace('.',','));forfaitDays.setText(p.getString("forfait_annual_days","").orEmpty().replace('.',','));monthlyGross.setText(p.getString("monthly_gross_salary","").orEmpty().replace('.',','));hourlyRate.setText(p.getString("hourly_rate","").orEmpty().replace('.',','));mealAmount.setText(p.getString("meal_amount","").orEmpty().replace('.',','));incomeTaxRate.setText(p.getString("income_tax_rate_percent","").orEmpty().replace('.',','));entryDate.setText(p.getString("entry_date","").orEmpty());updateContractFields();updateStatus(c)}
    private fun clearFields(){contractType.setSelection(0);listOf(weeklyHours,forfaitHours,forfaitDays,monthlyGross,hourlyRate,mealAmount,incomeTaxRate,entryDate).forEach{it.setText("")};status.text="⚠️ Ouvre d’abord une entreprise depuis MES ENTREPRISES."}
    private fun setFormEnabled(e:Boolean){contractType.isEnabled=e;listOf(weeklyHours,forfaitHours,forfaitDays,monthlyGross,hourlyRate,mealAmount,incomeTaxRate,entryDate).forEach{it.isEnabled=e};findViewWithTag<Button>("information_sheet_save")?.isEnabled=e}
    private fun num(v:EditText)=v.text.toString().trim().replace(',','.').toDoubleOrNull()
    private fun save(){val c=company?:return;val contract=contractValue(contractType.selectedItemPosition);if(contract.isBlank()){Toast.makeText(context,"Choisis le type de contrat",Toast.LENGTH_LONG).show();return};val date=entryDate.text.toString().trim();if(date.isBlank()){entryDate.error="Indique la date d’entrée";return};val weekly=num(weeklyHours);val fh=num(forfaitHours);val fd=num(forfaitDays);val gross=num(monthlyGross);val rate=num(hourlyRate);when(contract){"FULL_TIME","PART_TIME","OTHER"->if(weekly==null||weekly<=0||weekly>80){weeklyHours.error="Durée hebdomadaire invalide";return};"FORFAIT_HEURES"->if(fh==null||fh<=0){forfaitHours.error="Indique les heures prévues par le forfait";return};"FORFAIT_JOURS"->{if(fd==null||fd<=0||fd>218){forfaitDays.error="Indique le nombre de jours du forfait (218 maximum standard)";return};if(gross==null||gross<=0){monthlyGross.error="Indique le salaire brut mensuel convenu";return}};"FORFAIT"->{status.text="⚠️ Ancien forfait : précise s’il s’agit d’un forfait heures ou jours.";return}}
        if(contract!="FORFAIT_JOURS"&&(rate==null||rate<=0)){hourlyRate.error="Indique un taux horaire brut valide";return};val tax=num(incomeTaxRate);if(incomeTaxRate.text.isNotBlank()&&(tax==null||tax<0||tax>100)){incomeTaxRate.error="Indique un taux entre 0 et 100 %";return}
        val e=SalaryCompanyStore.prefs(context,c.id).edit().putString("contract_type",contract).putString("entry_date",date);fun put(k:String,v:Double?){if(v!=null)e.putString(k,v.toString())else e.remove(k)};put("contract_weekly_hours",if(contract in listOf("FULL_TIME","PART_TIME","OTHER"))weekly else null);put("forfait_annual_hours",if(contract=="FORFAIT_HEURES")fh else null);put("forfait_annual_days",if(contract=="FORFAIT_JOURS")fd else null);put("monthly_gross_salary",if(contract=="FORFAIT_JOURS")gross else null);put("hourly_rate",if(contract!="FORFAIT_JOURS")rate else null);put("meal_amount",num(mealAmount));put("income_tax_rate_percent",tax);if(!e.commit()){Toast.makeText(context,"Échec de l’enregistrement",Toast.LENGTH_LONG).show();return};updateStatus(c);Toast.makeText(context,"Fiche enregistrée pour ${c.name.ifBlank{"l’entreprise"}}",Toast.LENGTH_SHORT).show()}
    private fun updateStatus(c:SalaryCompanyStore.Company){val p=SalaryCompanyStore.prefs(context,c.id);val m=mutableListOf<String>();when(p.getString("contract_type","").orEmpty()){"FORFAIT_HEURES"->if(p.getString("forfait_annual_hours","").orEmpty().toDoubleOrNull()==null)m+="heures du forfait";"FORFAIT_JOURS"->{if(p.getString("forfait_annual_days","").orEmpty().toDoubleOrNull()==null)m+="jours du forfait";if(p.getString("monthly_gross_salary","").orEmpty().toDoubleOrNull()==null)m+="salaire brut mensuel"};"FORFAIT"->m+="type de forfait à préciser";""->m+="type de contrat";else->{if(p.getString("contract_weekly_hours","").orEmpty().toDoubleOrNull()==null)m+="durée hebdomadaire";if(p.getString("hourly_rate","").orEmpty().toDoubleOrNull()==null)m+="taux horaire"}};if(p.getString("entry_date","").isNullOrBlank())m+="date d’entrée";if(p.getString("income_tax_rate_percent","").orEmpty().toDoubleOrNull()==null)m+="taux PAS";status.text=if(m.isEmpty())"✅ Fiche complète pour cette entreprise" else "⚠️ À compléter : ${m.joinToString(", ")}"}
    private fun keepAwakeTemporarily(){val a=context as? Activity?:return;a.window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);removeCallbacks(stopAwake);postDelayed(stopAwake,AWAKE_MS)};private fun clearKeepAwake(){(context as? Activity)?.window?.clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)}
    private fun field(h:String,t:Int=InputType.TYPE_CLASS_TEXT)=EditText(context).apply{hint=h;inputType=t;isSingleLine=true;textSize=14f;background=controlBackground();setPadding(dp(12),dp(7),dp(12),dp(7))};private fun addLabel(s:String){addView(TextView(context).apply{text=s;textSize=13f;setTypeface(typeface,Typeface.BOLD);setTextColor(accentColor);setPadding(0,dp(12),0,0)})};private fun themedAdapter(i:List<String>)=ArrayAdapter(context,android.R.layout.simple_spinner_dropdown_item,i);private fun applyPanelBackground(v:View){v.background=when(theme.id){"natural_carbon"->CarbonCompositeDrawable(context);else->context.getDrawable(R.drawable.hp_panel)?.mutate()}};private fun controlBackground()=GradientDrawable().apply{shape=GradientDrawable.RECTANGLE;setColor(panelColor);setStroke(dp(1),accentColor);cornerRadius=dp(16).toFloat()};private fun applyThemeRecursively(v:View){if(v is TextView){v.setTextColor(textColor);if(v is EditText)v.setHintTextColor(hintColor)};if(v is ViewGroup)for(i in 0 until v.childCount)applyThemeRecursively(v.getChildAt(i))};private fun rowParams()=LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(52)).apply{topMargin=dp(6)}
    private fun contractIndex(v:String)=when(v.uppercase()){"FULL_TIME"->1;"PART_TIME"->2;"FORFAIT_HEURES"->3;"FORFAIT_JOURS"->4;"FORFAIT"->5;"OTHER"->6;else->0};private fun contractValue(i:Int)=when(i){1->"FULL_TIME";2->"PART_TIME";3->"FORFAIT_HEURES";4->"FORFAIT_JOURS";5->"FORFAIT";6->"OTHER";else->""};private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
}
