name: HPTravail
options:
  bundleIdPrefix: com.amaury
settings:
  base:
    SWIFT_VERSION: 5.9
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: 8.0.0
targets:
  HPTravail:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - HPTravail
    dependencies:
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: GoogleSignIn
        product: GoogleSignIn
    info:
      path: HPTravail/Info.plist
      properties:
        CFBundleDisplayName: HP Travail
        UILaunchScreen: {}
        NSLocationWhenInUseUsageDescription: HP Travail utilise ponctuellement votre position pendant l'utilisation de l'application.
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - com.googleusercontent.apps.827513765896-1123kjunj8pn19b487jpctq101qfr22l
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amaury.hptravail
        PRODUCT_NAME: HP Travail
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
